# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/dialogs/enter_custom_port_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_custom_port_dialog(object):
    def setupUi(self, custom_port_dialog):
        custom_port_dialog.setObjectName("custom_port_dialog")
        custom_port_dialog.resize(400, 69)
        self.verticalLayout = QtWidgets.QVBoxLayout(custom_port_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_hlayout = QtWidgets.QHBoxLayout()
        self.main_hlayout.setObjectName("main_hlayout")
        self.custom_port_label = QtWidgets.QLabel(custom_port_dialog)
        self.custom_port_label.setObjectName("custom_port_label")
        self.main_hlayout.addWidget(self.custom_port_label)
        self.custom_port_lineedit = QtWidgets.QLineEdit(custom_port_dialog)
        self.custom_port_lineedit.setObjectName("custom_port_lineedit")
        self.main_hlayout.addWidget(self.custom_port_lineedit)
        self.verticalLayout.addLayout(self.main_hlayout)
        self.button_box = QtWidgets.QDialogButtonBox(custom_port_dialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)
        self.custom_port_label.setBuddy(self.custom_port_lineedit)

        self.retranslateUi(custom_port_dialog)
        self.button_box.accepted.connect(custom_port_dialog.accept) # type: ignore
        self.button_box.rejected.connect(custom_port_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(custom_port_dialog)

    def retranslateUi(self, custom_port_dialog):
        _translate = QtCore.QCoreApplication.translate
        custom_port_dialog.setWindowTitle(_translate("custom_port_dialog", "sercom: Enter a custom port"))
        self.custom_port_label.setText(_translate("custom_port_dialog", "&Enter a custom port:"))
