# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/dialogs/set_baud_rate_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_baud_rate_dialog(object):
    def setupUi(self, baud_rate_dialog):
        baud_rate_dialog.setObjectName("baud_rate_dialog")
        baud_rate_dialog.resize(174, 69)
        self.verticalLayout = QtWidgets.QVBoxLayout(baud_rate_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_hlayout = QtWidgets.QHBoxLayout()
        self.main_hlayout.setObjectName("main_hlayout")
        self.baud_rate_label = QtWidgets.QLabel(baud_rate_dialog)
        self.baud_rate_label.setObjectName("baud_rate_label")
        self.main_hlayout.addWidget(self.baud_rate_label)
        self.baud_rate_combobox = QtWidgets.QComboBox(baud_rate_dialog)
        self.baud_rate_combobox.setEditable(True)
        self.baud_rate_combobox.setObjectName("baud_rate_combobox")
        self.main_hlayout.addWidget(self.baud_rate_combobox)
        self.verticalLayout.addLayout(self.main_hlayout)
        self.button_box = QtWidgets.QDialogButtonBox(baud_rate_dialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)
        self.baud_rate_label.setBuddy(self.baud_rate_combobox)

        self.retranslateUi(baud_rate_dialog)
        self.button_box.accepted.connect(baud_rate_dialog.accept) # type: ignore
        self.button_box.rejected.connect(baud_rate_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(baud_rate_dialog)

    def retranslateUi(self, baud_rate_dialog):
        _translate = QtCore.QCoreApplication.translate
        baud_rate_dialog.setWindowTitle(_translate("baud_rate_dialog", "sercom: Set a baud rate"))
        self.baud_rate_label.setText(_translate("baud_rate_dialog", "&Baud rate:"))
        self.baud_rate_combobox.setToolTip(_translate("baud_rate_dialog", "Type or select a baud rate"))
        self.baud_rate_combobox.setStatusTip(_translate("baud_rate_dialog", "Type or select a baud rate"))
        self.baud_rate_combobox.setPlaceholderText(_translate("baud_rate_dialog", "Type a baud rate..."))
