# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(800, 600)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        main_window.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(main_window)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menu_bar.setObjectName("menu_bar")
        self.menu_file = QtWidgets.QMenu(self.menu_bar)
        self.menu_file.setObjectName("menu_file")
        self.menu_port = QtWidgets.QMenu(self.menu_bar)
        self.menu_port.setObjectName("menu_port")
        self.menu_connect_to_port = QtWidgets.QMenu(self.menu_port)
        self.menu_connect_to_port.setObjectName("menu_connect_to_port")
        main_window.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(main_window)
        self.status_bar.setObjectName("status_bar")
        main_window.setStatusBar(self.status_bar)
        self.action_new_session = QtWidgets.QAction(main_window)
        self.action_new_session.setObjectName("action_new_session")
        self.action_exit = QtWidgets.QAction(main_window)
        self.action_exit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.action_exit.setObjectName("action_exit")
        self.action_enter_custom_port = QtWidgets.QAction(main_window)
        self.action_enter_custom_port.setObjectName("action_enter_custom_port")
        self.action_disconnect = QtWidgets.QAction(main_window)
        self.action_disconnect.setObjectName("action_disconnect")
        self.menu_file.addAction(self.action_new_session)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_port.addAction(self.menu_connect_to_port.menuAction())
        self.menu_port.addAction(self.action_disconnect)
        self.menu_bar.addAction(self.menu_file.menuAction())
        self.menu_bar.addAction(self.menu_port.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "sercom"))
        self.menu_file.setTitle(_translate("main_window", "&File"))
        self.menu_port.setTitle(_translate("main_window", "&Port"))
        self.menu_connect_to_port.setTitle(_translate("main_window", "&Connect to port"))
        self.action_new_session.setText(_translate("main_window", "&New session..."))
        self.action_new_session.setShortcut(_translate("main_window", "Ctrl+N"))
        self.action_exit.setText(_translate("main_window", "&Exit"))
        self.action_exit.setShortcut(_translate("main_window", "Ctrl+Q"))
        self.action_enter_custom_port.setText(_translate("main_window", "Enter &custom port..."))
        self.action_disconnect.setText(_translate("main_window", "&Disconnect"))
