import logging

from PyQt5.QtWidgets import QMainWindow

from ui.autogenerated.main_window import Ui_main_window
from utils.logger import create_logger

logger = create_logger(name=__name__, level=logging.DEBUG)


class sercomView(QMainWindow, Ui_main_window):
    """
    sercom's view where the GUI components are assembled.
    """

    def __init__(self):
        """
        Initialize the view.
        """
        logger.debug(f"Creating view")
        super().__init__()
        self.setupUi(self)
